name: Build EXEs + Installers + Ubuntu .deb

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  build_win7:
    name: Windows 7 EXE + Installer
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.7"]
        architecture: ["x64"]
    steps:
      - uses: actions/checkout@v4

      - name: Convert PNG to ICO
        shell: pwsh
        run: |
          $png = "icon\passport_extractor.png"
          $ico = "icon\passport_extractor.ico"
          magick convert $png $ico

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-win7.txt
          pip install pillow pyinstaller opencv-python

      - name: Copy cascades
        run: |
          python -c "import cv2, os, shutil; \
          os.makedirs('data', exist_ok=True); \
          [shutil.copy(os.path.join(cv2.data.haarcascades,f),'data') for f in ['haarcascade_frontalface_default.xml','haarcascade_eye.xml']]"

      - name: Build EXE
        shell: pwsh
        run: |
          pyinstaller --onefile --noconsole `
          "main.py" `
          --name passport_extractor_win7_${{ matrix.architecture }} `
          --add-data "data\haarcascade_frontalface_default.xml;data" `
          --add-data "data\haarcascade_eye.xml;data" `
          --add-data "models\res10_300x300_ssd_iter_140000.caffemodel;models" `
          --add-data "models\deploy.prototxt;models" `
          --hidden-import cv2 --hidden-import numpy

      - name: Build Inno Setup Installer
        shell: pwsh
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" "installer-win7.iss"

      - uses: actions/upload-artifact@v4
        with:
          name: Windows7-Artifacts
          path: |
            dist\passport_extractor_win7_${{ matrix.architecture }}.exe
            Output\SmartPassportCropper-Win7-Setup.exe

  build_win10:
    name: Windows 10 EXE + Installer
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.10"]
        architecture: ["x64"]
    steps:
      - uses: actions/checkout@v4

      - name: Convert PNG to ICO
        shell: pwsh
        run: |
          magick convert icon\passport_extractor.png icon\passport_extractor.ico

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pillow pyinstaller opencv-python

      - name: Copy cascades
        run: |
          python -c "import cv2, os, shutil; \
          os.makedirs('data', exist_ok=True); \
          [shutil.copy(os.path.join(cv2.data.haarcascades,f),'data') for f in ['haarcascade_frontalface_default.xml','haarcascade_eye.xml']]"

      - name: Build EXE
        shell: pwsh
        run: |
          pyinstaller --onefile --noconsole `
          "main.py" `
          --name passport_extractor_win10_${{ matrix.architecture }} `
          --add-data "data\haarcascade_frontalface_default.xml;data" `
          --add-data "data\haarcascade_eye.xml;data" `
          --add-data "models\res10_300x300_ssd_iter_140000.caffemodel;models" `
          --add-data "models\deploy.prototxt;models" `
          --hidden-import cv2 --hidden-import numpy

      - name: Build Inno Setup Installer
        shell: pwsh
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" "installer-win10.iss"

      - uses: actions/upload-artifact@v4
        with:
          name: Windows10-Artifacts
          path: |
            dist\passport_extractor_win10_${{ matrix.architecture }}.exe
            Output\SmartPassportCropper-Win10-Setup.exe

  build_ubuntu:
    name: Ubuntu 18.04 .deb
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Build in Ubuntu 18.04 container
        uses: addnab/docker-run-action@v3
        with:
          image: ubuntu:18.04
          options: -v ${{ github.workspace }}:/workspace -w /workspace
          run: |
            set -e
            apt-get update
            apt-get install -y software-properties-common
            add-apt-repository -y ppa:deadsnakes/ppa
            apt-get update
            apt-get install -y python3.7 python3.7-dev python3.7-distutils python3-pip \
                               build-essential imagemagick libgl1 libglib2.0-0

            python3.7 -m pip install --upgrade pip
            pip3 install -r requirements-linux.txt
            pip3 install pyinstaller pillow opencv-python

            mkdir -p data
            python3.7 -c "import cv2, os, shutil; \
            [shutil.copy(os.path.join(cv2.data.haarcascades,f),'data') for f in ['haarcascade_frontalface_default.xml','haarcascade_eye.xml']]"

            pyinstaller --onefile --noconsole "main.py" --name passport_extractor \
              --add-data "data/haarcascade_frontalface_default.xml:data" \
              --add-data "data/haarcascade_eye.xml:data" \
              --add-data "models/res10_300x300_ssd_iter_140000.caffemodel:models" \
              --add-data "models/deploy.prototxt:models" \
              --hidden-import=cv2 --hidden-import=numpy

            mkdir -p package/DEBIAN package/usr/bin package/usr/share/applications package/usr/share/icons/hicolor/256x256/apps
cat <<EOF > package/DEBIAN/control
Package: passport-extractor
Version: 1.0-3.7
Section: utils
Priority: optional
Architecture: amd64
Depends:
Maintainer: Kasim K <your-email@example.com>
Description: Smart Passport Photo Cropper v4 (offline installer)
 Extract and crop passport-size photos automatically.
EOF

            cp dist/passport_extractor package/usr/bin/
            cat <<EOF > package/usr/share/applications/passport_extractor.desktop
[Desktop Entry]
Version=1.0
Name=Passport Extractor
Comment=Smart Passport Photo Cropper
Exec=passport_extractor
Icon=passport_extractor
Terminal=false
Type=Application
Categories=Graphics;
EOF

            magick icon/passport_extractor.png package/usr/share/icons/hicolor/256x256/apps/passport_extractor.png
            dpkg-deb --build package passport_extractor_ubuntu18.deb

      - uses: actions/upload-artifact@v4
        with:
          name: Ubuntu18-Artifacts
          path: passport_extractor_ubuntu18.deb
